"""add_real_ev_tracking

Revision ID: 8afc7d011e3e
Revises: 
Create Date: 2025-12-17 22:41:25.941518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8afc7d011e3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ev_gate_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('archetype', sa.String(length=50), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=True),
    sa.Column('market_regime', sa.String(length=50), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('selected_level', sa.String(length=10), nullable=True),
    sa.Column('selected_key', sa.String(length=200), nullable=True),
    sa.Column('real_ev', sa.Float(), nullable=True),
    sa.Column('rolling_ev', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('user_action', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ev_gate_log_created_at'), 'ev_gate_log', ['created_at'], unique=False)
    op.create_index('ix_ev_gate_log_status', 'ev_gate_log', ['status'], unique=False)
    op.create_index('ix_ev_gate_log_user_created', 'ev_gate_log', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ev_gate_log_user_id'), 'ev_gate_log', ['user_id'], unique=False)
    op.create_table('ev_group_state',
    sa.Column('group_key', sa.String(length=200), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('disabled_until', sa.DateTime(), nullable=True),
    sa.Column('disable_reason', sa.String(length=50), nullable=True),
    sa.Column('last_eval_at', sa.DateTime(), nullable=False),
    sa.Column('last_real_ev', sa.Float(), nullable=True),
    sa.Column('last_rolling_ev', sa.Float(), nullable=True),
    sa.Column('last_sample_size', sa.Integer(), nullable=True),
    sa.Column('last_winrate', sa.Float(), nullable=True),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.Column('override_by', sa.Integer(), nullable=True),
    sa.Column('override_until', sa.DateTime(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('group_key')
    )
    op.add_column('trades', sa.Column('r_result', sa.Float(), nullable=True))
    op.add_column('trades', sa.Column('market_regime', sa.String(length=50), nullable=True))
    op.create_index('ix_trades_archetype_tf_closed', 'trades', ['scenario_archetype', 'timeframe', 'closed_at'], unique=False)
    op.create_index('ix_trades_regime_closed', 'trades', ['market_regime', 'closed_at'], unique=False)
    op.create_index('ix_trades_status_closed_at', 'trades', ['status', 'closed_at'], unique=False)
    # ### end Alembic commands ###

    # === BACKFILL existing trades ===
    # r_result = NET PnL / risk_usd
    op.execute("""
        UPDATE trades
        SET r_result = (pnl_usd - COALESCE(total_fees_usd, 0) - COALESCE(funding_usd, 0)) / risk_usd
        WHERE status = 'closed' AND risk_usd > 0 AND r_result IS NULL;
    """)

    # market_regime from scenario_snapshot JSON
    op.execute("""
        UPDATE trades
        SET market_regime = CONCAT(
            scenario_snapshot->'market_context'->>'trend',
            '_',
            scenario_snapshot->'market_context'->>'phase'
        )
        WHERE scenario_snapshot IS NOT NULL
          AND scenario_snapshot->'market_context' IS NOT NULL
          AND market_regime IS NULL;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_status_closed_at', table_name='trades')
    op.drop_index('ix_trades_regime_closed', table_name='trades')
    op.drop_index('ix_trades_archetype_tf_closed', table_name='trades')
    op.drop_column('trades', 'market_regime')
    op.drop_column('trades', 'r_result')
    op.drop_table('ev_group_state')
    op.drop_index(op.f('ix_ev_gate_log_user_id'), table_name='ev_gate_log')
    op.drop_index('ix_ev_gate_log_user_created', table_name='ev_gate_log')
    op.drop_index('ix_ev_gate_log_status', table_name='ev_gate_log')
    op.drop_index(op.f('ix_ev_gate_log_created_at'), table_name='ev_gate_log')
    op.drop_table('ev_gate_log')
    # ### end Alembic commands ###
